# Generated by Django 3.0.3 on 2020-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='')),
                ('whatsapp', models.IntegerField(default='')),
                ('email', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
