# Generated by Django 3.0.3 on 2020-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hm', '0002_auto_20200715_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='district',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='join',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='join',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
